acl Safe_ports port 80
#acl SSL_ports port 443

http_access deny !Safe_ports
#http_access deny CONNECT !SSL_ports
http_access allow all

http_port 3128

cache_mem 4 GB
maximum_object_size_in_memory 1 GB
maximum_object_size 4 GB

cache_dir aufs /mnt/cache/squid 10240 16 256

coredump_dir /var/spool/squid

refresh_pattern -i (/cgi-bin/|\?) 0 0% 0
refresh_pattern . 0 20% 4320





#acl snmppublic snmp_community public
#snmp_port 3401
#snmp_access allow all